os: linux
dist: bionic
#language: node_js
services:
    - docker

before_install:
    - docker build -t ualban/docker-react -f Dockerfile.dev .

script:
    - docker run ualban/docker-react npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "eu-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket: "elasticbeanstalk-eu-south-1-394948524389"
    bucket_path: "docker-react"
    on:
        branch: "master"
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"