sudo: required
language: node_js
services:
    - docker

before_install:
    - docker build -t ualban/docker-react -f Dockerfile.dev .

script:
    - docker run ualban/docker-react npm run test -- --watchAll=false